# Generated by Django 6.0.3 on 2026-03-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_itempareoencabezado_itempareodetalle_and_more'),
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('porcentaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('puntaje_ganado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_posible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_identificacion', to='respuestas.intentoprueba')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('puntaje_ganado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_posible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_pareo', to='respuestas.intentoprueba')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itempareoencabezado')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaRespuestaUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('puntaje_ganado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_posible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_abiertas', to='respuestas.intentoprueba')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemrespuestaunica')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField()),
                ('puntaje_ganado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_posible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_seleccion', to='respuestas.intentoprueba')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemseleccionunica')),
            ],
        ),
    ]
