# Generated by Django 6.0.3 on 2026-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0002_remove_respuestarespuestaunica_respuesta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoprueba',
            name='correo_confirmacion_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentoprueba',
            name='fecha_confirmacion_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentoprueba',
            name='hash_entrega',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
