# Generated by Django 6.0.3 on 2026-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0003_intentoprueba_correo_confirmacion_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoprueba',
            name='correo_calificacion_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentoprueba',
            name='fecha_calificacion_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaidentificacion',
            name='comentario_profesor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestapareo',
            name='comentario_profesor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestarespuestaunica',
            name='comentario_profesor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaseleccion',
            name='comentario_profesor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
