# Generated by Django 6.0.3 on 2026-03-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte1', models.TextField(blank=True, null=True)),
                ('parte2', models.TextField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSeleccionUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcion1', models.TextField()),
                ('opcion2', models.TextField()),
                ('opcion3', models.TextField()),
                ('opcion4', models.TextField()),
                ('opcion5', models.TextField(blank=True, null=True)),
                ('opcion6', models.TextField(blank=True, null=True)),
                ('opcion7', models.TextField(blank=True, null=True)),
                ('numero_opcion_correcta', models.IntegerField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('resultado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_seleccion', to='core.resultadoaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSeleccionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.documento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='items.itemseleccionunica')),
            ],
            options={
                'unique_together': {('item', 'documento')},
            },
        ),
    ]
