# Generated by Django 6.0.3 on 2026-03-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('items', '0002_itemrespuestaunica_itemrespuestadocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('resultado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_identificacion', to='core.resultadoaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='ItemIdentificacionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada_x', models.CharField(max_length=30)),
                ('coordenada_y', models.CharField(max_length=30)),
                ('respuesta_correcta', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='items.itemidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemIdentificacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.documento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='items.itemidentificacion')),
            ],
            options={
                'unique_together': {('item', 'documento')},
            },
        ),
    ]
