# Generated by Django 6.0.3 on 2026-03-18 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('items', '0003_itemidentificacion_itemidentificacioncomponente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPareoEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('resultado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pareo', to='core.resultadoaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPareoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='items.itempareoencabezado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPareoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.documento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='items.itempareoencabezado')),
            ],
            options={
                'unique_together': {('item', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='ItemPareoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_derecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_derecha', to='items.itempareodetalle')),
                ('item_izquierda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_izquierda', to='items.itempareodetalle')),
            ],
            options={
                'unique_together': {('item_izquierda', 'item_derecha')},
            },
        ),
    ]
