# Generated by Django 6.0.3 on 2026-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itempareoencabezado_itempareodetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
