# Generated by Django 6.0.3 on 2026-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_documento_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrespuestaunica',
            name='usa_latex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemseleccionunica',
            name='usa_latex',
            field=models.BooleanField(default=False),
        ),
    ]
