# Generated by Django 6.0.3 on 2026-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemrespuestaunica_usa_latex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='blob_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
