# Generated by Django 6.0.3 on 2026-04-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_documento_blob_name_documento_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='parte1',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='parte2',
        ),
    ]
