# Generated by Django 6.0.3 on 2026-04-16 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_perfiles_existentes(apps, schema_editor):
    User = apps.get_model("auth", "User")
    PerfilUsuario = apps.get_model("usuarios", "PerfilUsuario")

    for user in User.objects.all():
        nombre = " ".join([value for value in [getattr(user, "first_name", ""), getattr(user, "last_name", "")] if value]).strip()
        PerfilUsuario.objects.get_or_create(
            usuario=user,
            defaults={
                "rol": "profesor",
                "nombre_completo": nombre or user.username,
            }
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='profesor', max_length=20)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(crear_perfiles_existentes, migrations.RunPython.noop),
    ]
