# Generated by Django 6.0.3 on 2026-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_estudiante',
            field=models.TextField(blank=True, null=True),
        ),
    ]
