# Generated by Django 6.0.3 on 2026-03-18 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_itempareoencabezado_itempareodetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('centro_educativo', models.CharField(blank=True, max_length=300, null=True)),
                ('asignatura', models.CharField(blank=True, max_length=300, null=True)),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(blank=True, max_length=100, null=True)),
                ('puntos_totales', models.IntegerField(blank=True, null=True)),
                ('porcentaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaItemIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemidentificacion')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_identificacion', to='pruebas.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaItemPareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itempareoencabezado')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pareo', to='pruebas.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaItemRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemrespuestaunica')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_respuesta', to='pruebas.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaItemSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemseleccionunica')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_seleccion', to='pruebas.prueba')),
            ],
        ),
    ]
