# Generated by Django 6.0.3 on 2026-04-16 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pruebas.prueba')),
            ],
            options={
                'unique_together': {('prueba', 'estudiante')},
            },
        ),
    ]
