# Generated by Django 6.0.3 on 2026-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_pruebaasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
