# Generated by Django 6.0.3 on 2026-04-16 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_prueba_duracion_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=30)),
                ('orden', models.IntegerField(default=1)),
                ('cantidad_requerida', models.IntegerField(default=1)),
                ('puntaje_objetivo', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('modo_respuesta', models.CharField(default='uno', max_length=30)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='pruebas.prueba')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pruebaitemidentificacion',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_identificacion', to='pruebas.pruebaparte'),
        ),
        migrations.AddField(
            model_name='pruebaitempareo',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_pareo', to='pruebas.pruebaparte'),
        ),
        migrations.AddField(
            model_name='pruebaitemrespuesta',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_respuesta', to='pruebas.pruebaparte'),
        ),
        migrations.AddField(
            model_name='pruebaitemseleccion',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_seleccion', to='pruebas.pruebaparte'),
        ),
    ]
